import ELK from 'elkjs/lib/elk.bundled.js';
import { DiagramAST } from '../diagramParser/ASTTypes';
import { LayoutResult } from './LayoutTypes';
import { estimateNodeWidth, estimateNodeHeight } from '../NodeSizeEstimator';

const elk = new ELK();

function mapDirection(dir: 'TD' | 'LR' | 'RL' | 'BT'): string {
    switch (dir) {
        case 'LR': return 'RIGHT';
        case 'RL': return 'LEFT';
        case 'BT': return 'UP';
        default: return 'DOWN';
    }
}

export async function computeElkLayout(ast: DiagramAST): Promise<LayoutResult> {
    const elkAlgorithm = {
        'flowchart': 'layered',
        'mindmap': 'mrtree',
        'sequence': 'box',
        'class': 'layered',
        'er': 'stress',
        'state': 'layered',
        'radial': 'radial',
        'custom': 'layered',
    }[ast.meta.type] || 'layered';

    const elkGraph = {
        id: 'root',
        layoutOptions: {
            'elk.algorithm': elkAlgorithm,
            'elk.direction': mapDirection(ast.meta.direction),
            'elk.spacing.nodeNode': '60',
            'elk.layered.spacing.nodeNodeBetweenLayers': '80',
            'elk.padding': '[top=60, left=60, bottom=60, right=60]',
            'elk.hierarchyHandling': 'INCLUDE_CHILDREN',
        },
        children: ast.nodes.map(node => ({
            id: node.id,
            width: estimateNodeWidth(node),
            height: estimateNodeHeight(node),
        })),
        edges: ast.edges.map(edge => ({
            id: edge.id,
            sources: [edge.source],
            targets: [edge.target],
        })),
    };

    try {
        const result = await elk.layout(elkGraph);
        const nodesResult: LayoutResult['nodes'] = {};
        const edgesResult: LayoutResult['edges'] = {};

        result.children?.forEach((child: any) => {
            // ELK places children relative to parent. Since root is 0,0, these are absolute.
            nodesResult[child.id] = {
                id: child.id,
                x: child.x || 0,
                y: child.y || 0,
                width: child.width || 80,
                height: child.height || 40,
            };
        });

        result.edges?.forEach((edge: any) => {
            if (!edge.id) return;

            const pointsList: { x: number; y: number }[] = [];

            // ELK edges have sections containing startPoint, endPoint, and bendPoints
            edge.sections?.forEach((section: any) => {
                if (section.startPoint) {
                    pointsList.push({ x: section.startPoint.x, y: section.startPoint.y });
                }
                section.bendPoints?.forEach((bend: any) => {
                    pointsList.push({ x: bend.x, y: bend.y });
                });
                if (section.endPoint) {
                    pointsList.push({ x: section.endPoint.x, y: section.endPoint.y });
                }
            });

            // fallback to node centers if no path generated by ELK
            if (pointsList.length === 0) {
                const sourceNode = nodesResult[edge.sources[0]];
                const targetNode = nodesResult[edge.targets[0]];
                if (sourceNode && targetNode) {
                    pointsList.push(
                        { x: sourceNode.x + sourceNode.width / 2, y: sourceNode.y + sourceNode.height / 2 },
                        { x: targetNode.x + targetNode.width / 2, y: targetNode.y + targetNode.height / 2 }
                    );
                }
            }

            edgesResult[edge.id] = {
                id: edge.id,
                points: pointsList,
            };
        });

        return {
            nodes: nodesResult,
            edges: edgesResult,
            totalWidth: (result as any).width || 800,
            totalHeight: (result as any).height || 600,
        };
    } catch (err) {
        console.error('ELK layout failed, falling back to simple grid:', err);
        // Simple fallback to grid:
        const nodesResult: LayoutResult['nodes'] = {};
        const edgesResult: LayoutResult['edges'] = {};

        ast.nodes.forEach((n, idx) => {
            nodesResult[n.id] = {
                id: n.id,
                x: (idx % 3) * 180,
                y: Math.floor(idx / 3) * 120,
                width: estimateNodeWidth(n),
                height: estimateNodeHeight(n),
            };
        });

        ast.edges.forEach(e => {
            const s = nodesResult[e.source];
            const t = nodesResult[e.target];
            if (s && t) {
                edgesResult[e.id] = {
                    id: e.id,
                    points: [
                        { x: s.x + s.width / 2, y: s.y + s.height / 2 },
                        { x: t.x + t.width / 2, y: t.y + t.height / 2 }
                    ]
                };
            }
        });

        return {
            nodes: nodesResult,
            edges: edgesResult,
            totalWidth: 800,
            totalHeight: 600,
        };
    }
}
